smbnetfs: update update 0.5.3a -> 0.6.0
It seems that updating smbnetfs to latest revision fixes build issues.
Also remove the blacklist allowing the plugin to build again.
Patches reworked to apply on 0.6.0.

Additionally handle missing libexecinfo (DEPENDS and LDFLAGS)
when building with musl else we are getting the following error:
| ../../git/src/common.c:7:10: fatal error: execinfo.h: No such file or directory
|  #include <execinfo.h>

Signed-off-by: Athanasios Oikonomou <athoik@gmail.com>
Signed-off-by: Armin Kuster <akuster808@gmail.com>